language: go

go:
  - 1.8.x

before_install:
  - go get -v github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

script:
  - make
  - make test
  - make test-cover

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
