endpoints:
- localhost:9042
op_timeout: 10000000000 # 10 seconds (creating a new keyspace is very slow on travis)
dial_timeout: 3000000000 # 3 seconds
redial_interval: 60000000000 # 60 seconds
protocol_version: 4
